export const ROUTES = {
  HOME: "/shoes",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  ORDERS: "/orders",
  HELP: "/help",
  LOGOUT: "/logout",
  OFFERS: "/offers",
  ORDER_RECEIVED: "/order-received",
  PRODUCT: "/products",
  ORDER: "/order",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  CONTACT: "/contact",
  SHOPS: "/shops",
  Return: "/return",
  Shipping: "/shipping",
};
